using Avalonia.Controls;
using CommunityToolkit.Mvvm.Messaging;
using Microsoft.Extensions.DependencyInjection;
using NexusMonitor.Core.Services;
using NexusMonitor.UI.Messages;
using NexusMonitor.UI.ViewModels;
using NexusMonitor.UI.Views;
using Serilog;

namespace NexusMonitor.UI;

/// <summary>
/// Code-behind for MainWindow.axaml.
/// Handles system-tray close behaviour: intercepts the close button,
/// either hides the window to tray or shows a one-time prompt.
/// </summary>
public partial class MainWindow : Window
{
    // Set to true after the user explicitly chose "Close Application"
    // so the second Close() call (inside ShowClosePromptAsync) isn't cancelled again.
    private bool _forceClose;

    // Guards SaveSession against firing more than once per app lifetime. With the
    // RequestAppExit() shutdown flow, OnClosing can legitimately run SaveSession from the
    // "Exit"/prompt path AND, later, from the ApplicationShutdown-reason guard when the
    // deferred TryShutdown()'s window sweep re-enters OnClosing for this same window. By that
    // second call, this window's PlatformImpl may already be torn down — Position's getter
    // returns (0,0) once disposed — so a second, late SaveSession() would clobber the correct
    // geometry saved by the first call with garbage. First call wins; every later call is a
    // no-op. Same single-fire pattern as _shutdownHandled (App.axaml.cs) and _exitRequested
    // (App.axaml.cs) elsewhere in this diff.
    private bool _sessionSaved;

    /// <summary>Set to true before calling <see cref="App.RequestAppExit"/> from the tray exit
    /// handler so OnClosing allows the close to proceed on Linux.</summary>
    internal static bool ForceQuitFromTray { get; set; }

    /// <summary>Resolved once, at construction, and reused for every shutdown-path access
    /// (<see cref="OnClosing"/>, <see cref="SaveSession"/>) instead of re-resolving from
    /// <see cref="App.Services"/> each time. This matters on macOS: Cmd+Q invokes
    /// <c>IClassicDesktopStyleApplicationLifetime.TryShutdown</c> directly, whose
    /// <c>ShutdownRequested</c> handler (see <c>App.axaml.cs</c>) disposes <see cref="App.Services"/>
    /// BEFORE the ensuing window-close cascade reaches this window's <see cref="OnClosing"/> — so
    /// resolving <see cref="SettingsService"/> fresh from <see cref="App.Services"/> at that point
    /// throws <see cref="ObjectDisposedException"/> from the already-disposed provider itself.
    /// Holding this reference sidesteps that entirely: <see cref="SettingsService"/> itself has no
    /// "disposed" guard that would make a later <see cref="SettingsService.Save"/> throw — its own
    /// <see cref="SettingsService.Dispose"/> just tears down its debounce timer and does one final
    /// flush, so continuing to use an already-disposed instance here is safe.</summary>
    private readonly SettingsService _settings = App.Services.GetRequiredService<SettingsService>();

    /// <summary>Resolved once, at construction, for the exact same reason as <see cref="_settings"/>
    /// above (see its doc comment for the macOS Cmd+Q shutdown-ordering root cause). This is the
    /// third instance of this bug class: <see cref="_settings"/> itself (f986a51) and the
    /// <c>App.axaml.cs</c> shutdown handler's captured locals (c093bdf) were the first two.
    /// <see cref="ShowClosePromptAsync"/> and <see cref="MaybeHideWidget"/> — both close-path-only —
    /// use this field instead of resolving <see cref="SettingsViewModel"/> from
    /// <see cref="App.Services"/> at close time. With this fix, no MainWindow close/shutdown path
    /// re-resolves anything from <see cref="App.Services"/> after construction.</summary>
    private readonly SettingsViewModel _settingsViewModel = App.Services.GetRequiredService<SettingsViewModel>();

    // NOTE: The parameterless constructor is auto-generated by the Avalonia XAML
    // compiler in MainWindow.axaml.g.cs — do NOT define one here.

    protected override void OnOpened(EventArgs e)
    {
        base.OnOpened(e);
#if LINUX
        // Prevent KDE/GNOME from drawing native title bar alongside the custom one
        SystemDecorations = SystemDecorations.BorderOnly;
#endif
    }

    protected override void OnClosing(WindowClosingEventArgs e)
    {
        base.OnClosing(e);

        // App-wide shutdown sweep (App.RequestAppExit() -> TryShutdown() -> DoShutdown's foreach
        // over every ownerless window) reaches MainWindow here with this reason. It must NEVER
        // cancel or re-prompt at this point: with ShutdownMode.OnExplicitShutdown, DoShutdown's
        // ignoreCancel is false (true only for the old force:true Shutdown() call, or
        // OnMainWindowClose mode — neither applies here), so e.Cancel = true here would abort the
        // ENTIRE app shutdown, not just this window's close. By the time CloseCore reaches here
        // with this reason, every real "quit" affordance has already funneled through
        // RequestAppExit() first, and ShutdownRequested (App.axaml.cs) has already run its
        // cleanup (services stopped, pop-outs/overlay closed, DI disposed) — this window's own
        // close just needs to save session state and get out of the way.
        if (e.CloseReason == WindowCloseReason.ApplicationShutdown)
        {
            SaveSession();
            return;
        }

        // Tray "Quit" on Linux: allow the close immediately
        if (ForceQuitFromTray) { SaveSession(); return; }

        // Already decided → let the OS close proceed
        if (_forceClose) { SaveSession(); return; }

        var settings = _settings;

        switch (settings.Current.CloseAction)
        {
            case "Tray" when settings.Current.MinimizeToTray:
                e.Cancel = true;
                Hide();
                WeakReferenceMessenger.Default.Send(new WindowVisibilityChangedMessage(false));
                MaybeHideWidget(settings.Current.HideWidgetOnMinimize);
                return;

            case "Exit":
                SaveSession();
                App.RequestAppExit();
                return; // allow normal close
        }

        // "" = always ask → cancel the close and show the prompt
        e.Cancel = true;
        _ = ShowClosePromptAsync(settings);
    }

    private async Task ShowClosePromptAsync(SettingsService settings)
    {
        try
        {
            var settingsVm = _settingsViewModel;
            var dialog     = new TrayPromptDialog(settingsVm.ShowOverlayWidget);

            // ShowDialog suspends here until the dialog closes
            var result = await dialog.ShowDialog<TrayPromptResult?>(this);
            if (result is null) return; // user dismissed (ESC / OS close)

            // Persist choice if requested
            if (result.Remember)
            {
                settings.Current.CloseAction          = result.Action;
                settings.Current.HideWidgetOnMinimize = result.HideWidget;
                settings.Save();
                // Also update Settings UI without firing save again (load backing fields)
                settingsVm.CloseActionIndex =
                    result.Action == "Tray" ? 1 :
                    result.Action == "Exit" ? 2 : 0;
                settingsVm.HideWidgetOnMinimize = result.HideWidget;
            }

            MaybeHideWidget(result.HideWidget);

            if (result.Action == "Tray")
            {
                Hide();
                WeakReferenceMessenger.Default.Send(new WindowVisibilityChangedMessage(false));
            }
            else
            {
                _forceClose = true;
                App.RequestAppExit();
                Close();
            }
        }
        catch (Exception ex)
        {
            // OnClosing cancels the close and calls this fire-and-forget (`_ = ShowClosePromptAsync(...)`)
            // because OnClosing cannot be awaited. Before this fix, an exception here (e.g. the
            // now-eliminated late App.Services.GetRequiredService<SettingsViewModel>() call above,
            // which could throw ObjectDisposedException once the provider was torn down) became an
            // unobserved task exception: nothing surfaced, e.Cancel was already true, and the window
            // never closed at all — under factory defaults (CloseAction == "") this made Quit
            // completely unusable on fresh installs. This is the third instance of the
            // disposed-provider-on-close bug class (MainWindow._settings field, f986a51; App
            // shutdown captures, c093bdf); every late Services resolution on a close/shutdown path is
            // now eliminated, but this catch stays as a hard backstop — fire-and-forget must never
            // let any exception vanish silently.
            Log.Error(ex, "Error showing close prompt");
        }
    }

    private void SaveSession()
    {
        if (_sessionSaved) return;
        _sessionSaved = true;

        var settings = _settings;
        var vm       = DataContext as MainViewModel;
        settings.Current.LastActiveTab   = vm?.SelectedNavItem?.Label ?? string.Empty;
        settings.Current.LastWindowState = WindowState.ToString();
        if (WindowState == WindowState.Normal)
        {
            settings.Current.LastWindowWidth  = Width;
            settings.Current.LastWindowHeight = Height;
            settings.Current.LastWindowX      = Position.X;
            settings.Current.LastWindowY      = Position.Y;
        }
        settings.Save();
    }

    private void MaybeHideWidget(bool hide)
    {
        if (!hide) return;
        _settingsViewModel.ShowOverlayWidget = false;
    }
}
