using Avalonia.Controls;
using CommunityToolkit.Mvvm.Messaging;
using Microsoft.Extensions.DependencyInjection;
using NexusMonitor.Core.Services;
using NexusMonitor.UI.Messages;
using NexusMonitor.UI.ViewModels;
using NexusMonitor.UI.Views;

namespace NexusMonitor.UI;

/// <summary>
/// Code-behind for MainWindow.axaml.
/// Handles system-tray close behaviour: intercepts the close button,
/// either hides the window to tray or shows a one-time prompt.
/// </summary>
public partial class MainWindow : Window
{
    // Set to true after the user explicitly chose "Close Application"
    // so the second Close() call (inside ShowClosePromptAsync) isn't cancelled again.
    private bool _forceClose;

    /// <summary>Set to true before calling desktop.Shutdown() from the tray exit handler
    /// so OnClosing allows the close to proceed on Linux.</summary>
    internal static bool ForceQuitFromTray { get; set; }

    // NOTE: The parameterless constructor is auto-generated by the Avalonia XAML
    // compiler in MainWindow.axaml.g.cs — do NOT define one here.

    protected override void OnOpened(EventArgs e)
    {
        base.OnOpened(e);
#if LINUX
        // Prevent KDE/GNOME from drawing native title bar alongside the custom one
        SystemDecorations = SystemDecorations.BorderOnly;
#endif
    }

    protected override void OnClosing(WindowClosingEventArgs e)
    {
        base.OnClosing(e);

        // Tray "Quit" on Linux: allow the close immediately
        if (ForceQuitFromTray) { SaveSession(); return; }

        // Already decided → let the OS close proceed
        if (_forceClose) { SaveSession(); return; }

        var settings = App.Services.GetRequiredService<SettingsService>();

        switch (settings.Current.CloseAction)
        {
            case "Tray" when settings.Current.MinimizeToTray:
                e.Cancel = true;
                Hide();
                WeakReferenceMessenger.Default.Send(new WindowVisibilityChangedMessage(false));
                MaybeHideWidget(settings.Current.HideWidgetOnMinimize);
                return;

            case "Exit":
                SaveSession();
                return; // allow normal close
        }

        // "" = always ask → cancel the close and show the prompt
        e.Cancel = true;
        _ = ShowClosePromptAsync(settings);
    }

    private async Task ShowClosePromptAsync(SettingsService settings)
    {
        var settingsVm = App.Services.GetRequiredService<SettingsViewModel>();
        var dialog     = new TrayPromptDialog(settingsVm.ShowOverlayWidget);

        // ShowDialog suspends here until the dialog closes
        var result = await dialog.ShowDialog<TrayPromptResult?>(this);
        if (result is null) return; // user dismissed (ESC / OS close)

        // Persist choice if requested
        if (result.Remember)
        {
            settings.Current.CloseAction          = result.Action;
            settings.Current.HideWidgetOnMinimize = result.HideWidget;
            settings.Save();
            // Also update Settings UI without firing save again (load backing fields)
            settingsVm.CloseActionIndex =
                result.Action == "Tray" ? 1 :
                result.Action == "Exit" ? 2 : 0;
            settingsVm.HideWidgetOnMinimize = result.HideWidget;
        }

        MaybeHideWidget(result.HideWidget);

        if (result.Action == "Tray")
        {
            Hide();
            WeakReferenceMessenger.Default.Send(new WindowVisibilityChangedMessage(false));
        }
        else
        {
            _forceClose = true;
            Close();
        }
    }

    private void SaveSession()
    {
        var settings = App.Services.GetRequiredService<SettingsService>();
        var vm       = DataContext as MainViewModel;
        settings.Current.LastActiveTab   = vm?.SelectedNavItem?.Label ?? string.Empty;
        settings.Current.LastWindowState = WindowState.ToString();
        if (WindowState == WindowState.Normal)
        {
            settings.Current.LastWindowWidth  = Width;
            settings.Current.LastWindowHeight = Height;
            settings.Current.LastWindowX      = Position.X;
            settings.Current.LastWindowY      = Position.Y;
        }
        settings.Save();
    }

    private static void MaybeHideWidget(bool hide)
    {
        if (!hide) return;
        App.Services.GetRequiredService<SettingsViewModel>().ShowOverlayWidget = false;
    }
}
