using NexusMonitor.Core.Models;

namespace NexusMonitor.Core.Themes;

public static class BuiltInThemePresets
{
    public static IReadOnlyList<ThemePreset> All { get; } = new ThemePreset[]
    {
        // Redefined quiet (owner-approved ruling 2026-07-11) to match AppSettings' new
        // fresh-install defaults exactly: glass/backdrop/specular off, ThemeMode "System"
        // (follows the OS instead of forcing Dark). Custom window/surface/sidebar hexes stay ""
        // (empty = derive from theme) — a literal hex here would trip the known theme-flip
        // stale-color bug.
        new() { Id = "nexus-default",    Name = "Nexus Default",    ThemeMode = "System", AccentColorHex = "#0A84FF", TextAccentColorHex = "",        CustomWindowBgHex = "",        CustomSurfaceBgHex = "",        CustomSidebarBgHex = "",        IsGlassEnabled = false, GlassOpacity = 0.80, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.55, FontFamily = "",                FontSizeMultiplier = 1.0 },
        // New (2026-07-11): carries the PREVIOUS "Nexus Default" showcase look verbatim (same
        // values, just renamed/re-IDed) so it stays available as an explicit opt-in preset.
        new() { Id = "crystal-glass",    Name = "Crystal Glass",    ThemeMode = "Dark",   AccentColorHex = "#0A84FF", TextAccentColorHex = "",        CustomWindowBgHex = "",        CustomSurfaceBgHex = "",        CustomSidebarBgHex = "",        IsGlassEnabled = true,  GlassOpacity = 0.80, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.55, FontFamily = "",                FontSizeMultiplier = 1.0 },
        new() { Id = "clean-light",      Name = "Clean Light",      ThemeMode = "Light", AccentColorHex = "#007AFF", TextAccentColorHex = "",        CustomWindowBgHex = "",        CustomSurfaceBgHex = "",        CustomSidebarBgHex = "",        IsGlassEnabled = false, GlassOpacity = 0.80, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.55, FontFamily = "",                FontSizeMultiplier = 1.0 },
        new() { Id = "neon",             Name = "Neon",             ThemeMode = "Dark",  AccentColorHex = "#39FF14", TextAccentColorHex = "#00FFFF", CustomWindowBgHex = "#0A0014", CustomSurfaceBgHex = "#0F0020", CustomSidebarBgHex = "#0D001A", IsGlassEnabled = true,  GlassOpacity = 0.70, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.70, FontFamily = "Orbitron",        FontSizeMultiplier = 1.0 },
        new() { Id = "cherry-blossom",   Name = "Cherry Blossom",   ThemeMode = "Light", AccentColorHex = "#E84393", TextAccentColorHex = "#D63384", CustomWindowBgHex = "#FFF0F5", CustomSurfaceBgHex = "#FFFFFF", CustomSidebarBgHex = "#FFF5F8", IsGlassEnabled = false, GlassOpacity = 0.85, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.30, FontFamily = "Quicksand",       FontSizeMultiplier = 1.0 },
        new() { Id = "dark-sakura",      Name = "Dark Sakura",      ThemeMode = "Dark",  AccentColorHex = "#FF6B9D", TextAccentColorHex = "#FFB0CC", CustomWindowBgHex = "#1A0F15", CustomSurfaceBgHex = "#231820", CustomSidebarBgHex = "#150B12", IsGlassEnabled = true,  GlassOpacity = 0.75, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.40, FontFamily = "Zen Maru Gothic", FontSizeMultiplier = 1.0 },
        new() { Id = "anime",            Name = "Anime",            ThemeMode = "Dark",  AccentColorHex = "#FF6B81", TextAccentColorHex = "#FFD93D", CustomWindowBgHex = "#1A0A1E", CustomSurfaceBgHex = "#221428", CustomSidebarBgHex = "#1E0F24", IsGlassEnabled = true,  GlassOpacity = 0.75, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.60, FontFamily = "Nunito",          FontSizeMultiplier = 1.0 },
        new() { Id = "futuristic",       Name = "Futuristic",       ThemeMode = "Dark",  AccentColorHex = "#00D4FF", TextAccentColorHex = "#00FFE0", CustomWindowBgHex = "#020D18", CustomSurfaceBgHex = "#081824", CustomSidebarBgHex = "#061420", IsGlassEnabled = true,  GlassOpacity = 0.65, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.80, FontFamily = "Rajdhani",        FontSizeMultiplier = 1.0 },
        new() { Id = "outer-space",      Name = "Outer Space",      ThemeMode = "Dark",  AccentColorHex = "#7C5CFC", TextAccentColorHex = "#B8A9FF", CustomWindowBgHex = "#05050F", CustomSurfaceBgHex = "#0C0C1A", CustomSidebarBgHex = "#080818", IsGlassEnabled = true,  GlassOpacity = 0.70, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.65, FontFamily = "Space Grotesk",   FontSizeMultiplier = 1.0 },
        new() { Id = "minimalist",       Name = "Minimalist",       ThemeMode = "Light", AccentColorHex = "#333333", TextAccentColorHex = "#555555", CustomWindowBgHex = "#FAFAFA", CustomSurfaceBgHex = "#FFFFFF", CustomSidebarBgHex = "#F5F5F5", IsGlassEnabled = false, GlassOpacity = 0.90, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.20, FontFamily = "",                FontSizeMultiplier = 1.0 },
        new() { Id = "deep-dark",        Name = "Deep Dark",        ThemeMode = "Dark",  AccentColorHex = "#BB86FC", TextAccentColorHex = "",        CustomWindowBgHex = "#000000", CustomSurfaceBgHex = "#0A0A0A", CustomSidebarBgHex = "#050505", IsGlassEnabled = false, GlassOpacity = 0.95, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.00, FontFamily = "",                FontSizeMultiplier = 1.0 },
        new() { Id = "magical",          Name = "Magical",          ThemeMode = "Dark",  AccentColorHex = "#E040FB", TextAccentColorHex = "#FFD740", CustomWindowBgHex = "#140A20", CustomSurfaceBgHex = "#1A1030", CustomSidebarBgHex = "#160C28", IsGlassEnabled = true,  GlassOpacity = 0.72, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.75, FontFamily = "Cinzel",          FontSizeMultiplier = 1.0 },
        new() { Id = "techno",           Name = "Techno",           ThemeMode = "Dark",  AccentColorHex = "#00FF9C", TextAccentColorHex = "#CCFF00", CustomWindowBgHex = "#0A0F0A", CustomSurfaceBgHex = "#101A10", CustomSidebarBgHex = "#0D150D", IsGlassEnabled = true,  GlassOpacity = 0.68, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.60, FontFamily = "Share Tech Mono", FontSizeMultiplier = 1.0 },
        new() { Id = "ocean-depth",      Name = "Ocean Depth",      ThemeMode = "Dark",  AccentColorHex = "#00BCD4", TextAccentColorHex = "#4DD0E1", CustomWindowBgHex = "#0A1620", CustomSurfaceBgHex = "#0F1E2C", CustomSidebarBgHex = "#0C1A26", IsGlassEnabled = true,  GlassOpacity = 0.78, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.50, FontFamily = "Exo 2",           FontSizeMultiplier = 1.0 },
        new() { Id = "sunset",           Name = "Sunset",           ThemeMode = "Dark",  AccentColorHex = "#FF7043", TextAccentColorHex = "#FFB74D", CustomWindowBgHex = "#1A0F0A", CustomSurfaceBgHex = "#241510", CustomSidebarBgHex = "#1E120D", IsGlassEnabled = true,  GlassOpacity = 0.75, BackdropBlurMode = "Acrylic", IsSpecularEnabled = true,  SpecularIntensity = 0.45, FontFamily = "Poppins",         FontSizeMultiplier = 1.0 },
        new() { Id = "arctic",           Name = "Arctic",           ThemeMode = "Light", AccentColorHex = "#0288D1", TextAccentColorHex = "#0277BD", CustomWindowBgHex = "#F0F8FF", CustomSurfaceBgHex = "#FFFFFF", CustomSidebarBgHex = "#E8F4FD", IsGlassEnabled = false, GlassOpacity = 0.85, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.25, FontFamily = "Nunito",          FontSizeMultiplier = 1.0 },
        new() { Id = "dracula",          Name = "Dracula",          ThemeMode = "Dark",  AccentColorHex = "#BD93F9", TextAccentColorHex = "#FF79C6", CustomWindowBgHex = "#282A36", CustomSurfaceBgHex = "#2D2F3D", CustomSidebarBgHex = "#21222C", IsGlassEnabled = false, GlassOpacity = 0.90, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.00, FontFamily = "Fira Code",       FontSizeMultiplier = 1.0 },
        new() { Id = "solarized-dark",   Name = "Solarized Dark",   ThemeMode = "Dark",  AccentColorHex = "#268BD2", TextAccentColorHex = "#2AA198", CustomWindowBgHex = "#002B36", CustomSurfaceBgHex = "#073642", CustomSidebarBgHex = "#002028", IsGlassEnabled = false, GlassOpacity = 0.90, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.00, FontFamily = "Fira Code",       FontSizeMultiplier = 1.0 },
        new() { Id = "solarized-light",  Name = "Solarized Light",  ThemeMode = "Light", AccentColorHex = "#268BD2", TextAccentColorHex = "#2AA198", CustomWindowBgHex = "#FDF6E3", CustomSurfaceBgHex = "#EEE8D5", CustomSidebarBgHex = "#FDF6E3", IsGlassEnabled = false, GlassOpacity = 0.90, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.00, FontFamily = "Fira Code",       FontSizeMultiplier = 1.0 },
        new() { Id = "nord",             Name = "Nord",             ThemeMode = "Dark",  AccentColorHex = "#88C0D0", TextAccentColorHex = "#81A1C1", CustomWindowBgHex = "#2E3440", CustomSurfaceBgHex = "#3B4252", CustomSidebarBgHex = "#2E3440", IsGlassEnabled = false, GlassOpacity = 0.88, BackdropBlurMode = "None",    IsSpecularEnabled = false, SpecularIntensity = 0.00, FontFamily = "",                FontSizeMultiplier = 1.0 },
    };
}
